SELECT DISTINCT AA.CAR_ID, 
CASE WHEN BB.CAR_ID IS NOT NULL THEN '대여중' ELSE '대여 가능'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AA
LEFT JOIN (SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE) BB
ON AA.CAR_ID = BB.CAR_ID
ORDER BY CAR_ID DESC;
